<a href="https://colab.research.google.com/github/19PA1A0548/Ai/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing numpy
import numpy as np 

In [ ]:
a = np.array([1,2,3]) #basic array
print(a)

[1 2 3]


In [ ]:
b = np.arange(1,10,2) #arange function
b

array([1, 3, 5, 7, 9])

In [ ]:
c = np.arange(10).reshape(2,5) #reshape function
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
a1 = np.reshape(c,(5,2))
print(a1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
a2 = np.arange(10).reshape(5,2)
print(a2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
cad = a1+a2 #Matrix addititon
print(cad)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [ ]:
#Matrix multiplication
mul1 = np.arange(9).reshape(3,3)
mul2 = np.arange(9).reshape(3,3)
print(mul1 @ mul2)
print(mul1.dot(mul2))
print(np.dot(mul1,mul2))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [ ]:
print(mul1.shape) #dimmensions of matrix

(3, 3)


In [ ]:
print(mul1.size) #total no.of elements

9


In [ ]:
print(mul2.ndim) #no.of dimmensions

2


In [ ]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.sin(30))

-0.9880316240928618


In [ ]:
print(mul1.sum(axis=1))
print(mul1.min())

[ 3 12 21]
0


In [ ]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr[1:,1:])
print(arr[:3,])
print(arr[:,:-1])

[[5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]


In [ ]:
for i in arr:
  for j in i:
    print(j)

for i in arr.flat:
  print(i)

1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [ ]:
arr.T
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
av = np.arange(1,5).reshape(2,2)
bv = np.arange(5,9).reshape(2,2)
print(av)
print(bv)
print(np.vstack((av,bv)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.hstack((av,bv)))

[[1 2 5 6]
 [3 4 7 8]]
